Вот обновленный код для твоего файла `.github/ISSUE_TEMPLATE/compatibility_report.yml`. Я добавил все версии, которые ты просил, от **0.5.0** до **0.13.0**, включая **0.12.5**.

Теперь в твоей форме будет подробный список, где для каждой версии эмулятора нужно выбрать статус.

```yaml
name: "Compatibility Report"
description: "Submit a detailed game report for all shadPS4 versions"
body:
  - type: checkboxes
    id: checkpoints
    attributes:
      label: "Important: Read first"
      options:
        - label: "I understand this is a Community list and all data types (dumps/pirated) are accepted"
          required: true
  - type: input
    id: game_name
    attributes:
      label: "1. Game Name"
      placeholder: "e.g., My Name is Mayo"
    validations:
      required: true
  - type: input
    id: game_id
    attributes:
      label: "2. Game ID (CUSA)"
      placeholder: "e.g., CUSA09306"
    validations:
      required: true
  - type: dropdown
    id: copy_type
    attributes:
      label: "3. Copy Type"
      options:
        - "Digital Dump (Own)"
        - "Physical Disc"
        - "Unofficial/Pirated"
    validations:
      required: true

  - type: dropdown
    id: ver_050
    attributes:
      label: "Status on v0.5.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_060
    attributes:
      label: "Status on v0.6.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_070
    attributes:
      label: "Status on v0.7.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_080
    attributes:
      label: "Status on v0.8.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_0100
    attributes:
      label: "Status on v0.10.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_0110
    attributes:
      label: "Status on v0.11.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_0120
    attributes:
      label: "Status on v0.12.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_0125
    attributes:
      label: "Status on v0.12.5"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true
  - type: dropdown
    id: ver_0130
    attributes:
      label: "Status on v0.13.0"
      options: ["Playable", "Trophies Only", "Crashes", "Not Tested"]
    validations:
      required: true

  - type: textarea
    id: error_details
    attributes:
      label: "7. Error Details"
      placeholder: "Explain the error (e.g., Error 0X80550006 on v0.13.0)"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "8. Solution / Fix"
      placeholder: "How to make it work? If no solution, write: nope"
    validations:
      required: true

```

### Что теперь изменится в твоем репозитории:

* **Полная история версий**: Тестеры смогут указать, что игра работала на **0.6.0** (Trophies Only), но сломалась на **0.13.0** (Crashes).
* **Звездочки для всех версий**: Так как стоит `required: true`, человеку придется выбрать хотя бы "Not Tested" для версий, которые он не проверял.
* **Профессиональный вид**: Теперь твой список выглядит даже подробнее, чем официальный, потому что ты отслеживаешь историю изменений.

**Хочешь, я помогу тебе обновить таблицу в README.md, чтобы она тоже отображала все эти версии для наглядности?**
