name: "Compatibility Report"
description: "Submit a detailed game report for all shadPS4 versions"
body:
  - type: checkboxes
    id: checkpoints
    attributes:
      label: "Important: Read first"
      options:
        - label: "I understand this is a Community list and all data types (dumps/pirated) are accepted"
          required: true
  - type: input
    id: game_name
    attributes:
      label: "1. Game Name"
      placeholder: "e.g., My Name is Mayo"
    validations:
      required: true
  - type: input
    id: game_id
    attributes:
      label: "2. Game ID (CUSA)"
      placeholder: "e.g., CUSA09306"
    validations:
      required: true
  - type: dropdown
    id: copy_type
    attributes:
      label: "3. Copy Type"
      options:
        - "Digital Dump (Own)"
        - "Physical Disc"
        - "Unofficial/Pirated"
    validations:
      required: true

  - &ver_status
    type: dropdown
    attributes:
      label: "Select status for version"
      options:
        - "Playable (Everything works)"
        - "Platinum (All trophies work / 100%)"
        - "Orange Status (Trophies work, but ONLY with original DualSense/DualShock 3-4)"
        - "White Status (Trophies work with ANY controller/keyboard)"
        - "In-Game (Plays but with glitches/issues)"
        - "Error/Crash (Game does not start or crashes)"
    validations:
      required: true

  - <<: *ver_status
    id: ver_050
    attributes:
      label: "Status on v0.5.0"
  - <<: *ver_status
    id: ver_060
    attributes:
      label: "Status on v0.6.0"
  - <<: *ver_status
    id: ver_070
    attributes:
      label: "Status on v0.7.0"
  - <<: *ver_status
    id: ver_080
    attributes:
      label: "Status on v0.8.0"
  - <<: *ver_status
    id: ver_0100
    attributes:
      label: "Status on v0.10.0"
  - <<: *ver_status
    id: ver_0110
    attributes:
      label: "Status on v0.11.0"
  - <<: *ver_status
    id: ver_0120
    attributes:
      label: "Status on v0.12.0"
  - <<: *ver_status
    id: ver_0125
    attributes:
      label: "Status on v0.12.5"
  - <<: *ver_status
    id: ver_0130
    attributes:
      label: "Status on v0.13.0"

  - type: textarea
    id: error_details
    attributes:
      label: "7. Error Details"
      placeholder: "Explain the error or details about trophies/controllers"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "8. Solution / Fix"
      placeholder: "How to make it work? If no solution, write: nope"
    validations:
      required: true
